# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinchModuleTransitions' do
  
  use_frameworks!

  pod 'SwiftLint'

  target 'FinchModuleTransitionsTests' do
    # Pods for testing
  end

end
